/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.Login;

import java.sql.SQLException;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        CheckUser checkUser = new CheckUser();
        Scanner scanner = new Scanner(System.in);
        int mode = 1;
        while (true) {
            if (mode == 1) {
                System.out.println("Chon 1 trong 2 chuc nang sau:" +
                        "\n" + "1. Sign In" +
                        "\n" + "0. Out");
                int a = Integer.parseInt(scanner.nextLine());
                while (a != 1 & a != 0) {
                    System.out.println("chon lai 1 trong 2!");
                    a = Integer.parseInt(scanner.nextLine());
                }
                if (a == 1) {
                    try {
                        System.out.println("Nhap username:");
                        String username = scanner.nextLine();
                        System.out.println("Nhap password:");
                        String password = scanner.nextLine();
                        if (checkUser.SignIn(username, password)) {
                            mode = 2;
                        }
                    } catch (SQLException | ClassNotFoundException e) {
                        System.out.println("error:" + e);
                    }
                } else {
                    System.exit(1);
                }
            } else {
                System.out.println("Chon 1 trong 2 chuc nang sau:" +
                        "\n" + "1. Sign Out" +
                        "\n" + "0. Out");
                int a = Integer.parseInt(scanner.nextLine());
                while (a != 1 & a != 0) {
                    System.out.println("chon lai 1 trong 2!");
                    a = Integer.parseInt(scanner.nextLine());
                }
                if (a == 1) {
                    mode = 1;
                } else {
                    System.exit(1);
                }
            }
        }
    }
}
