/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.Login;

import java.sql.SQLException;
import java.util.Scanner;

public class App {
    public static void main(String[] args) throws SQLException, ClassNotFoundException {
        User user = new User();
        Scanner scanner = new Scanner(System.in);
        int mode = 0;
        while (mode != 4) {
            System.out.println("Chon chuc nang:" +
                    "\n1. Sign In" +
                    "\n2. Sign Up" +
                    "\n3. Delete" +
                    "\n4. Out");
            mode = Integer.parseInt(scanner.nextLine());
            switch (mode) {
                case 1: {
                    System.out.println("username:");
                    String username = scanner.nextLine();
                    System.out.println("password:");
                    String password = scanner.nextLine();
                    user.SignIn(username, password);
                    break;
                }
                case 2: {
                    System.out.println("username:");
                    String username = scanner.nextLine();
                    System.out.println("password:");
                    String password = scanner.nextLine();
                    user.SignUp(username, password);
                    break;
                }
                case 3: {
                    System.out.println("username:");
                    String username = scanner.nextLine();
                    user.Delete(username);
                    break;
                }
                case 4: {
                    System.exit(1);
                }
                default: {
                    System.out.println("Chon lai");
                    break;
                }
            }
        }
    }
}
